const CATALOG = [
    //СЕРИЯ ESTEL PRIMA BLOND (ЭСТЕЛЬ ПРИМА БЛОНД) ДЛЯ СВЕТЛЫХ ВОЛОС
    {
        id: 'el1',
        name: 'СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE',
        img: '../../main/img/estel-prima-blond/СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE.webp',
        quantity: 2,
        price: 450,
    },
    {
        id: 'el2',
        name: 'СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ',
        img: '../../main/img/estel-prima-blond/СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ.webp',
        price: 900,
        quantity: 1,
    },
    {
        id: 'el3',
        name: 'СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE',
        img: '../../main/img/estel-prima-blond/СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el4',
        name: 'СЕРЕБРИСТАЯ МАСКА ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE',
        img: '../../main/img/estel-prima-blond/СЕРЕБРИСТАЯ МАСКА ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE.webp',
        price: 650,
        quantity: 1,
    },
    {
        id: 'el5',
        name: 'БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: '../../main/img/estel-prima-blond/БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el6',
        name: 'БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE, 1000 МЛ',
        img: '../../main/img/estel-prima-blond/БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE, 1000 МЛ.webp',
        price: 900,
        quantity: 1,
    },
    {
        id: 'el7',
        name: 'БЛЕСК-БАЛЬЗАМ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: '../../main/img/estel-prima-blond/БЛЕСК-БАЛЬЗАМ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el8',
        name: 'КОМФОРТ-МАСКА ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: '../../main/img/estel-prima-blond/КОМФОРТ-МАСКА ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 650,
        quantity: 1,
    },
    {
        id: 'el9',
        name: 'ДВУХФАЗНЫЙ СПРЕЙ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: '../../main/img/estel-prima-blond/ДВУХФАЗНЫЙ СПРЕЙ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el10',
        name: 'МАСЛО-УХОД ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: '../../main/img/estel-prima-blond/МАСЛО-УХОД ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 650,
        quantity: 1,
    },
    {
        id: 'el11',
        name: 'СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ',
        img: '../../main/img/estel-prima-blond/СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ.webp',
        price: 1050,
        quantity: 1,
    },
    //ТОНИРУЮЩИЕ МАСКИ NEWTONE HAUTE COUTURE, 60 МЛ
    {
        id: 'el12',
        name: 'NEWTONE 10-6, СВЕТЛЫЙ БЛОНДИН ФИОЛЕТОВЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 10-6, СВЕТЛЫЙ БЛОНДИН ФИОЛЕТОВЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el13',
        name: 'NEWTONE 10-7, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 10-7, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el14',
        name: 'NEWTONE 10-76, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВО-ФИОЛЕТОВЫЙ, 60 МЛ.webp',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 10-76, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВО-ФИОЛЕТОВЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el15',
        name: 'NEWTONE 7-34, РУСЫЙ ЗОЛОТИСТО-МЕДНЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 7-34, РУСЫЙ ЗОЛОТИСТО-МЕДНЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el16',
        name: 'NEWTONE 7-44, РУСЫЙ МЕДНЫЙ ИНТЕНСИВНЫЙ, 60 МЛ.webp',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 7-44, РУСЫЙ МЕДНЫЙ ИНТЕНСИВНЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el17',
        name: 'NEWTONE 7-56, РУСЫЙ КРАСНО-ФИОЛЕТОВЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 7-56, РУСЫЙ КРАСНО-ФИОЛЕТОВЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el18',
        name: 'NEWTONE 7-75, РУСЫЙ КОРИЧНЕВО-КРАСНЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 7-75, РУСЫЙ КОРИЧНЕВО-КРАСНЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el19',
        name: 'NEWTONE 8-36, СВЕТЛО-РУСЫЙ ЗОЛОТИСТО-ФИОЛЕТОВЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 8-36, СВЕТЛО-РУСЫЙ ЗОЛОТИСТО-ФИОЛЕТОВЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el20',
        name: 'NEWTONE 8-61, СВЕТЛО-РУСЫЙ ФИОЛЕТОВО-ПЕПЕЛЬНЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 8-61, СВЕТЛО-РУСЫЙ ФИОЛЕТОВО-ПЕПЕЛЬНЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el21',
        name: 'NEWTONE 8-76, СВЕТЛО-РУСЫЙ КОРИЧНЕВО-ФИОЛЕТОВЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 8-76, СВЕТЛО-РУСЫЙ КОРИЧНЕВО-ФИОЛЕТОВЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el22',
        name: 'NEWTONE 9-65, БЛОНДИН ФИОЛЕТОВО-КРАСНЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 9-65, БЛОНДИН ФИОЛЕТОВО-КРАСНЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
    {
        id: 'el123',
        name: 'NEWTONE 10-73, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВО-ЗОЛОТИСТЫЙ, 60 МЛ',
        img: '../../main/img/NEWTONE HAUTE COUTURE/NEWTONE 10-73, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВО-ЗОЛОТИСТЫЙ, 60 МЛ.webp',
        price: 150,
        quantity: 1,
    },
];